"""create trips table

Revision ID: 02053c65955c
Revises: eae4d3daf73d
Create Date: 2026-09-30 15:12:06.873337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02053c65955c'
down_revision: Union[str, None] = 'eae4d3daf73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('start_odometer', sa.Float(), nullable=True),
    sa.Column('end_odometer', sa.Float(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_car_id'), 'trips', ['car_id'], unique=False)
    op.create_index('ix_trips_car_status', 'trips', ['car_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index('ix_trips_driver_status', 'trips', ['driver_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index('ix_trips_start_datetime', 'trips', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index('ix_trips_start_datetime', table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index('ix_trips_driver_status', table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index('ix_trips_car_status', table_name='trips')
    op.drop_index(op.f('ix_trips_car_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
