"""create expenses table

Revision ID: 0bd70a84b308
Revises: 02053c65955c
Create Date: 2026-10-01 11:34:55.813363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0bd70a84b308"
down_revision: Union[str, None] = "02053c65955c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses",
        sa.Column(
            "status", sa.String(length=20), nullable=False, server_default="active"
        ),
    )
    op.add_column(
        "expenses", sa.Column("category", sa.String(length=50), nullable=False)
    )
    op.add_column("expenses", sa.Column("vendor", sa.String(length=150), nullable=True))
    op.add_column(
        "expenses", sa.Column("payment_method", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "expenses", sa.Column("receipt_number", sa.String(length=100), nullable=True)
    )
    op.add_column("expenses", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("expenses", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index(
        "ix_expenses_car_category", "expenses", ["car_id", "category"], unique=False
    )
    op.create_index(
        "ix_expenses_car_date", "expenses", ["car_id", "expense_date"], unique=False
    )
    op.create_index(op.f("ix_expenses_car_id"), "expenses", ["car_id"], unique=False)
    op.create_index(
        op.f("ix_expenses_category"), "expenses", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_expense_date"), "expenses", ["expense_date"], unique=False
    )
    op.drop_constraint("expenses_car_id_fkey", "expenses", type_="foreignkey")
    op.create_foreign_key(
        None, "expenses", "cars", ["car_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_column("expenses", "expense_type")
    op.drop_column("expenses", "creates_at")
    op.drop_column("expenses", "expenses_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'status')
    op.add_column(
        "expenses",
        sa.Column("expenses_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "expenses",
        sa.Column(
            "creates_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "expenses",
        sa.Column("expense_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "expenses", type_="foreignkey")
    op.create_foreign_key(
        "expenses_car_id_fkey", "expenses", "cars", ["car_id"], ["id"]
    )
    op.drop_index(op.f("ix_expenses_expense_date"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_category"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_car_id"), table_name="expenses")
    op.drop_index("ix_expenses_car_date", table_name="expenses")
    op.drop_index("ix_expenses_car_category", table_name="expenses")
    op.drop_column("expenses", "created_at")
    op.drop_column("expenses", "notes")
    op.drop_column("expenses", "receipt_number")
    op.drop_column("expenses", "payment_method")
    op.drop_column("expenses", "vendor")
    op.drop_column("expenses", "category")
    op.drop_column("expenses", "expense_date")
    # ### end Alembic commands ###
