"""add drivers table

Revision ID: 1559435bf2cf
Revises: 6713a923b204
Create Date: 2026-09-29 16:29:59.213131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1559435bf2cf'
down_revision: Union[str, None] = '6713a923b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_issue_date', sa.Date(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_license_expiry_date'), 'drivers', ['license_expiry_date'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_index(op.f('ix_drivers_name'), 'drivers', ['name'], unique=False)
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=True)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_index('ix_drivers_status_expiry', 'drivers', ['status', 'license_expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drivers_status_expiry', table_name='drivers')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_expiry_date'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
