"""sync car and user constraints

Revision ID: 33ed9cbba3be
Revises: 62d354277ca4
Create Date: 2026-09-07 12:30:38.101681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ed9cbba3be'
down_revision: Union[str, None] = '62d354277ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cars', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cars_owner_id'), 'cars', ['owner_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_cars_owner_id'), table_name='cars')
    op.alter_column('cars', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cars', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
