"""add driver and trip links to expenses

Revision ID: 58decb844cdb
Revises: cd24051295eb
Create Date: 2026-10-01 18:00:48.575872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58decb844cdb'
down_revision: Union[str, None] = 'cd24051295eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_index('ix_expenses_driver_date', 'expenses', ['driver_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_driver_id'), 'expenses', ['driver_id'], unique=False)
    op.create_index('ix_expenses_trip_date', 'expenses', ['trip_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_trip_id'), 'expenses', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'trips', ['trip_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'expenses', 'drivers', ['driver_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_trip_id'), table_name='expenses')
    op.drop_index('ix_expenses_trip_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_driver_id'), table_name='expenses')
    op.drop_index('ix_expenses_driver_date', table_name='expenses')
    op.drop_column('expenses', 'trip_id')
    op.drop_column('expenses', 'driver_id')
    # ### end Alembic commands ###
