"""add vehicle documents

Revision ID: 6713a923b204
Revises: 6e83e7033d37
Create Date: 2026-09-29 10:07:04.808528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6713a923b204'
down_revision: Union[str, None] = '6e83e7033d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_documents_car_id'), 'vehicle_documents', ['car_id'], unique=False)
    op.create_index('ix_vehicle_documents_car_type', 'vehicle_documents', ['car_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_document_type'), 'vehicle_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_expiry_date'), 'vehicle_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_id'), 'vehicle_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_documents_id'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_expiry_date'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_document_type'), table_name='vehicle_documents')
    op.drop_index('ix_vehicle_documents_car_type', table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_car_id'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    # ### end Alembic commands ###
