"""add fuel records

Revision ID: 6e83e7033d37
Revises: 33ed9cbba3be
Create Date: 2026-09-23 11:38:10.314382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e83e7033d37'
down_revision: Union[str, None] = '33ed9cbba3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('fuel_date', sa.Date(), nullable=False),
    sa.Column('odometer_reading', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('litres', sa.Float(), nullable=False),
    sa.Column('price_per_litre', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('fuel_station', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_records_car_id'), 'fuel_records', ['car_id'], unique=False)
    op.create_index(op.f('ix_fuel_records_fuel_date'), 'fuel_records', ['fuel_date'], unique=False)
    op.create_index(op.f('ix_fuel_records_id'), 'fuel_records', ['id'], unique=False)
    op.create_index(op.f('ix_services_car_id'), 'services', ['car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_car_id'), table_name='services')
    op.drop_index(op.f('ix_fuel_records_id'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_fuel_date'), table_name='fuel_records')
    op.drop_index(op.f('ix_fuel_records_car_id'), table_name='fuel_records')
    op.drop_table('fuel_records')
    # ### end Alembic commands ###
