"""add expense status

Revision ID: cd24051295eb
Revises: 0bd70a84b308
Create Date: 2026-10-01 12:17:53.835388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd24051295eb'
down_revision: Union[str, None] = '0bd70a84b308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_column('expenses', 'status')
    # ### end Alembic commands ###
