"""add driver vehicle assignments

Revision ID: eae4d3daf73d
Revises: 1559435bf2cf
Create Date: 2026-09-29 17:22:17.435095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae4d3daf73d'
down_revision: Union[str, None] = '1559435bf2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_vehicle_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('assigned_from', sa.Date(), nullable=False),
    sa.Column('assigned_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_vehicle_assignments_assigned_from'), 'driver_vehicle_assignments', ['assigned_from'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_assignments_assigned_to'), 'driver_vehicle_assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_assignments_car_id'), 'driver_vehicle_assignments', ['car_id'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_assignments_driver_id'), 'driver_vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_assignments_id'), 'driver_vehicle_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_assignments_status'), 'driver_vehicle_assignments', ['status'], unique=False)
    op.create_index('ix_driver_vehicle_car_status', 'driver_vehicle_assignments', ['car_id', 'status'], unique=False)
    op.create_index('ix_driver_vehicle_driver_status', 'driver_vehicle_assignments', ['driver_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_driver_vehicle_driver_status', table_name='driver_vehicle_assignments')
    op.drop_index('ix_driver_vehicle_car_status', table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_status'), table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_id'), table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_driver_id'), table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_car_id'), table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_assigned_to'), table_name='driver_vehicle_assignments')
    op.drop_index(op.f('ix_driver_vehicle_assignments_assigned_from'), table_name='driver_vehicle_assignments')
    op.drop_table('driver_vehicle_assignments')
    # ### end Alembic commands ###
