"""add report download history

Revision ID: f405b2955611
Revises: 62722f20c7ef
Create Date: 2026-10-06 15:10:23.774123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f405b2955611'
down_revision: Union[str, None] = '62722f20c7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_download_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_download_history_created_at'), 'report_download_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_download_history_export_format'), 'report_download_history', ['export_format'], unique=False)
    op.create_index(op.f('ix_report_download_history_id'), 'report_download_history', ['id'], unique=False)
    op.create_index('ix_report_download_history_report_format', 'report_download_history', ['report_type', 'export_format'], unique=False)
    op.create_index(op.f('ix_report_download_history_report_type'), 'report_download_history', ['report_type'], unique=False)
    op.create_index('ix_report_download_history_user_date', 'report_download_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_report_download_history_user_id'), 'report_download_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_download_history_user_id'), table_name='report_download_history')
    op.drop_index('ix_report_download_history_user_date', table_name='report_download_history')
    op.drop_index(op.f('ix_report_download_history_report_type'), table_name='report_download_history')
    op.drop_index('ix_report_download_history_report_format', table_name='report_download_history')
    op.drop_index(op.f('ix_report_download_history_id'), table_name='report_download_history')
    op.drop_index(op.f('ix_report_download_history_export_format'), table_name='report_download_history')
    op.drop_index(op.f('ix_report_download_history_created_at'), table_name='report_download_history')
    op.drop_table('report_download_history')
    # ### end Alembic commands ###
